/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.iniris.preciodelaluz;

public final class R {
    public static final class attr {
    }
    public static final class bool {
        /** Enable automatic activity tracking
         */
        public static final int ga_autoActivityTracking=0x7f050000;
        /** Enable automatic exception tracking
         */
        public static final int ga_reportUncaughtExceptions=0x7f050001;
    }
    public static final class drawable {
        public static final int icono=0x7f020000;
    }
    public static final class integer {
        public static final int ga_dispatchPeriod=0x7f060000;
    }
    public static final class string {
        public static final int app_name=0x7f040003;
        public static final int ga_appName=0x7f040001;
        public static final int ga_appVersion=0x7f040002;
        /** Replace placeholder ID with your tracking ID
         */
        public static final int ga_trackingId=0x7f040000;
    }
    public static final class xml {
        public static final int config=0x7f030000;
    }
}
